### ISSUE TITLE
reading Xsens file

### ISSUE THREAD

**Issue by MohameHassan** [EmbodiedCognition/py-c3d#11] opened 2018-05-29 13:44 UTC
I have a c3d file exported from MVNX studio of xsens. When I try to read the file using your library. I get the following error:

`
>>> import c3d
 >>> f = open('test.c3d','rb')
 >>> data = c3d.Reader(f)
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/is/ps2/mhassan/.virtualenvs/frankengeist/local/lib/python2.7/site-packages/c3d.py", line 796, in __init__
     self.check_metadata()
   File "/is/ps2/mhassan/.virtualenvs/frankengeist/local/lib/python2.7/site-packages/c3d.py", line 534, in check_metadata
     assert self.header.frame_rate == self.point_rate, (
   File "/is/ps2/mhassan/.virtualenvs/frankengeist/local/lib/python2.7/site-packages/c3d.py", line 674, in point_rate
     return self.get_float('POINT:RATE')
   File "/is/ps2/mhassan/.virtualenvs/frankengeist/local/lib/python2.7/site-packages/c3d.py", line 657, in get_float
     return self.get(key).float_value
AttributeError: 'NoneType' object has no attribute 'float_value' 
`

**Comment by kbsmale** [comment] 2018-07-27 13:09
Hi MohameHassan,

This isn't actually a py-c3d error but actually an Xsens error.[ Here](https://base.xsens.com/hc/en-us/community/posts/360003601993-Parsing-c3d-file) on their support thread they admit to the bug, which should be fixed in the newest release due out next month (Aug. 2018)

**Comment by lmjohns3** [comment] 2018-07-30 21:41
Will close for now, please reopen if the issue is still present with the updated xsens file.

**Closed by lmjohns3** 2018-07-30 21:41 UTC
